Initial structure
grpc-queue/grpc-queue pull request #3
Opened 2021-01-28 02:07 UTC by ap-pauloafonso

This is the initial structure for the project, its pretty basic, but i think with this we can start implementing the broker!
closes #1 , #2

2021-02-02 16:24 UTC, ap-pauloafonso commented
@damianopetrungaro i forgot to tag you, sorry about that. i thought that you would the the notification with just the pr.

2021-02-08 15:01 UTC, damianopetrungaro requested changes
Sorry for the delay!
Here there are some inputs we may do together in a pair-programming session 💪

2021-02-08 15:01 UTC, damianopetrungaro commented on internal/queueproto/queueproto.proto
> +syntax = "proto3";
Using the golang standard project layout we want to use, we should move this into the  `/api/proto/v1` directory, what do you think?

2021-02-08 23:54 UTC, ap-pauloafonso commented
Wow  that's a lot of good points @damianopetrungaro , i love it. so should i start addressing this points, or will we do this on our pair programming session? also could you confirm what date will be our meeting?

2021-02-09 10:52 UTC, damianopetrungaro commented
> i love it. so should i start addressing this points, or will we do this on our pair programming session
Up to you!
> also out next meeting will be February 13th right?
yeag sadly i am super busy those weeks :(

2021-02-14 21:14 UTC, ap-pauloafonso commented on cmd/client/main.go
> +	if len(os.Args) == 1 {
Oh, yes i totally forgot about that , i used it on ratio-spoof, nice catch!

2021-02-14 21:16 UTC, ap-pauloafonso commented on cmd/client/main.go
> +	operation := os.Args[1]
I forgot to delete this SayHello thing, it was basically to  test the grpc request/response is working as expected.

2021-02-14 21:21 UTC, ap-pauloafonso commented on cmd/client/main.go
> +	default:
Makes total sense, i thought that i would need it in order to test the communication between the server and the client, But now i realize that the client is intended to use as a imported package in another projects,  right?
So for now i will comment the entire file, and if you allow me, i will delete it forever.

2021-02-14 21:21 UTC, ap-pauloafonso commented on cmd/server/main.go
> +
Done ;)

2021-02-14 21:25 UTC, ap-pauloafonso commented on internal/client/client.go
> +package client
Done ;)
Oh, i didn't know about that, so all the third party packages that we  import on our projects are only available because the devs put it on pkg/ folder? i thought that was just a convention...

2021-02-14 21:27 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.pb.go
> +// Code generated by protoc-gen-go. DO NOT EDIT.
I moved to pkg/grpc/v1/queue, what do you think?

2021-02-14 21:30 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.proto
> +
Done ;)
I think i followed an older tutorial on grpc, that didn't mentioned it, and it generated only 1 pb.go file(older way)  as oposed to 2 pb.go files (newer way).

2021-02-14 21:31 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.proto
> +  string body = 1;
Basically it was a test that i forgot to delete. now its deleted ;)

2021-02-14 21:33 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.proto
> +  string payload = 3;
Good catch, i didn't thought about that, the contract now uses bytes.

2021-02-14 21:33 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.proto
> +  string payload = 1;
Good catch, i didn't thought about that, the contract now uses bytes.

2021-02-14 21:33 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.proto
> +  rpc SayHello(Message) returns (Message) {}
No we don't, it was just for my initial tests, now it's deleted.

2021-02-14 21:39 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.proto
> +
So i decided to use this contract(let me know if this is ok), but with one change on the CreateStreamRequest object, basically i added an option to pass how many partitions do we want for this stream/topic. What do you think? i have never used kafka, does it make sense?

2021-02-14 21:42 UTC, ap-pauloafonso commented on internal/server/server.go
> +package server
I thought that the cmd folder is like a simple entrypoint layer, and all the heavy stuff(such as broker implementation) goes on the internal folder. I didn't change it yet, but if you want i can change it :)

2021-02-14 21:43 UTC, ap-pauloafonso commented on internal/queueproto/queueproto.proto
> +syntax = "proto3";
Done ;) let me know what you think

2021-02-14 21:51 UTC, ap-pauloafonso commented
Before 
`
├── cmd
│   ├── client
│   │   └── main.go
│   └── server
│       └── main.go
├── go.mod
├── go.sum
└── internal
    ├── client
    │   └── client.go
    ├── queueproto
    │   ├── queueproto.pb.go
    │   └── queueproto.proto
    └── server
        └── server.go
 `
After
`
├── api
│   └── proto
│       └── v1
│           └── queue.proto
├── cmd
│   ├── client
│   │   └── main.go (commented)
│   └── server
│       └── main.go
├── go.mod
├── go.sum
├── internal
│   └── server
│       └── server.go
├── pkg
│   ├── client
│   │   └── client.go
│   └── grpc
│       └── v1
│           └── queue
│               ├── queue_grpc.pb.go
│               └── queue.pb.go
└── README
`

2021-02-16 16:22 UTC, damianopetrungaro commented on README
> +protoc --go_out=. --go-grpc_out=. api/proto/v1/queue.proto
Add this as a Makefile command:
`make generate-grpc`

2021-02-16 16:23 UTC, damianopetrungaro commented on README
> +protoc --go_out=. --go-grpc_out=. api/proto/v1/queue.proto
Assigned to @damianopetrungaro

2021-02-16 16:26 UTC, damianopetrungaro commented on api/proto/v1/queue.proto
> +  Error error = 1;
add partition (optional, default can be assumed here)

2021-02-16 16:26 UTC, damianopetrungaro commented on api/proto/v1/queue.proto
> +  Stream stream = 1;
add partition (optional, default can be assumed here)

2021-02-16 16:28 UTC, damianopetrungaro commented on api/proto/v1/queue.proto
> +  rpc Push(PushItemRequest) returns (PushItemResponse){}
I need to double check this, but it should look like that 
```suggestion
  rpc Push(PushItemRequest) returns (stream PushItemResponse){}
```

2021-02-16 16:40 UTC, damianopetrungaro commented on pkg/client/client.go
> +	response, err := service.CreateStream(context.Background(), req)
We need to pass the context ;)

2021-02-16 16:42 UTC, damianopetrungaro commented on pkg/client/client.go
> +	address string
add a connection field

2021-02-16 16:46 UTC, damianopetrungaro commented on pkg/client/client.go
> +	return &client{address: address}
maybe we can pass a connection here?

2021-02-16 16:57 UTC, damianopetrungaro commented on pkg/client/client.go
> +		log.Fatalf("Error when calling Push: %s", err)
```suggestion
		return fmt.Errorf("%w: %s", YourCustomError, err)
```

2021-02-18 21:03 UTC, ap-pauloafonso commented on api/proto/v1/queue.proto
> +  Error error = 1;
You mean the PopItemRequest?
https://github.com/grpc-queue/grpc-queue/blob/eb961e4b36ecb42f7951b9a9a900f24ddea9bc80/api/proto/v1/queue.proto#L11-L14
So basically the stream object already has the partition field, so i guess we won't need it, what do you think?

2021-02-18 21:03 UTC, ap-pauloafonso commented on api/proto/v1/queue.proto
> +  Stream stream = 1;
https://github.com/grpc-queue/grpc-queue/blob/eb961e4b36ecb42f7951b9a9a900f24ddea9bc80/api/proto/v1/queue.proto#L11-L14
So basically the stream object already has the partition field, so i guess we won't need it, what do you think?

2021-02-18 21:10 UTC, ap-pauloafonso commented on api/proto/v1/queue.proto
> +  rpc Push(PushItemRequest) returns (PushItemResponse){}
Seems like the keyword is **repeated**, So the file would be sort of like this:
before:
``` proto
syntax = "proto3";
package queue;

option go_package = "pkg/grpc/v1/queue";

message Error {
  int32 code = 1;
  string reason = 2;
}

message Stream {
  string name = 1;
  int32 partition = 2;
}

message Streams {
  repeated Stream streams = 1;
}

message CreateStreamRequest {
  string name = 1;
  int32 partitionCount =2;
}

message CreateStreamResponse {
  Error errors = 1;
}

message GetStreamsRequest{
  Stream stream = 1;
  repeated int32 partitions = 2;
}

message GetStreamsResponse{
  oneof message {
    Streams streams = 1;
    Error error = 2;
  }
}

message Item {
  bytes payload = 1;
}

message PushItemRequest {
  Stream stream = 1;
  Item item = 2;
}

message PushItemResponse {
  Error error = 1;
}

message PopItemRequest{
  Stream stream = 1;
}

message PopItemResponse{
  oneof message {
    Item item = 1;
    Error error = 2;
  }
}

service QueueService {
  rpc CreateStream(CreateStreamRequest) returns (CreateStreamResponse){}
  rpc GetStreams(GetStreamsRequest)returns (GetStreamsResponse){}
  rpc Push(PushItemRequest) returns (PushItemResponse){}
  rpc Pop(PopItemRequest) returns (PopItemResponse){}
}

```
After:
``` proto
syntax = "proto3";
package queue;

option go_package = "pkg/grpc/v1/queue";

message Error {
  int32 code = 1;
  string reason = 2;
}

message Stream {
  string name = 1;
  int32 partition = 2;
}

message Streams {
  repeated Stream streams = 1;
}

message CreateStreamRequest {
  string name = 1;
  int32 partitionCount =2;
}

message CreateStreamResponse {
  Error errors = 1;
}

message GetStreamsRequest{
  Stream stream = 1;
  repeated int32 partitions = 2;
}

message GetStreamsResponse{
  oneof message {
    Streams streams = 1;
    Error error = 2;
  }
}

message Item {
  bytes payload = 1;
}

message PushItemRequest {
  Stream stream = 1;
  Item item = 2;
}

message PushItemResponse {
  Error error = 1;
}

message PopItemRequest{
  Stream stream = 1;
  int32 quantity =2;
}

message PopedItem {
  oneof message{
    Item item = 1;
    Error error = 2;
  }
}

message PopItemResponse{
  repeated PopedItem PopedItem =1;
}

service QueueService {
  rpc CreateStream(CreateStreamRequest) returns (CreateStreamResponse){}
  rpc GetStreams(GetStreamsRequest)returns (GetStreamsResponse){}
  rpc Push(PushItemRequest) returns (PushItemResponse){}
  rpc Pop(PopItemRequest) returns (PopItemResponse){}
}

```
*also i added a **quantity** on the poprequest
I didn't make the change yet, let me know what do you think about this ;)

2021-02-18 21:13 UTC, ap-pauloafonso commented on pkg/client/client.go
> +	response, err := service.CreateStream(context.Background(), req)
done ;)

2021-02-18 21:14 UTC, ap-pauloafonso commented on pkg/client/client.go
> +	return &client{address: address}
done ;)

2021-02-18 21:15 UTC, ap-pauloafonso commented on pkg/client/client.go
> +	address string
done ;)

2021-02-18 21:21 UTC, ap-pauloafonso commented on README
> +protoc --go_out=. --go-grpc_out=. api/proto/v1/queue.proto
I did try to write one, let me know what you think ;)

2021-02-18 21:22 UTC, ap-pauloafonso commented on pkg/client/client.go
> +		log.Fatalf("Error when calling Push: %s", err)
done :)

2021-02-18 21:31 UTC, ap-pauloafonso commented
I addressed all but the proto-file comments, i left a comment there explaining why, after that we can proceed with the implementation

2021-02-24 15:57 UTC, damianopetrungaro commented on api/proto/v1/queue.proto
> +  Stream stream = 1;
noice!

2021-02-24 15:57 UTC, damianopetrungaro commented on api/proto/v1/queue.proto
> +  Error error = 1;
noice

2021-03-02 16:07 UTC, damianopetrungaro approved these changes

2021-03-02 16:08 UTC, merged